window.quizQuestions = [
{subject:"Maths",question:"What is 1 + 2?",options:["2","3","4","5"],answer:"3"},
{subject:"Maths",question:"What is 2 + 4?",options:["5","6","7","8"],answer:"6"},
{subject:"Maths",question:"What is 3 + 5?",options:["7","8","9","10"],answer:"8"},
{subject:"Maths",question:"What is 4 + 6?",options:["9","10","11","12"],answer:"10"},
{subject:"Maths",question:"What is 5 + 7?",options:["11","12","13","14"],answer:"12"},
{subject:"Maths",question:"What is 6 + 8?",options:["13","14","15","16"],answer:"14"},
{subject:"Maths",question:"What is 7 + 9?",options:["15","16","17","18"],answer:"16"},
{subject:"Maths",question:"What is 8 + 10?",options:["17","18","19","20"],answer:"18"},
{subject:"Maths",question:"What is 9 + 11?",options:["19","20","21","22"],answer:"20"},
{subject:"Maths",question:"What is 10 + 12?",options:["21","22","23","24"],answer:"22"},
{subject:"Maths",question:"What is 11 + 13?",options:["23","24","25","26"],answer:"24"},
{subject:"Maths",question:"What is 12 + 14?",options:["25","26","27","28"],answer:"26"},
{subject:"Maths",question:"What is 13 + 15?",options:["27","28","29","30"],answer:"28"},
{subject:"Maths",question:"What is 14 + 16?",options:["29","30","31","32"],answer:"30"},
{subject:"Maths",question:"What is 15 + 17?",options:["31","32","33","34"],answer:"32"},
{subject:"Maths",question:"What is 16 + 18?",options:["33","34","35","36"],answer:"34"},
{subject:"Maths",question:"What is 17 + 19?",options:["35","36","37","38"],answer:"36"},
{subject:"Maths",question:"What is 18 + 20?",options:["37","38","39","40"],answer:"38"},
{subject:"Maths",question:"What is 19 + 21?",options:["39","40","41","42"],answer:"40"},
{subject:"Maths",question:"What is 20 + 22?",options:["41","42","43","44"],answer:"42"},
{subject:"Maths",question:"What is 21 + 23?",options:["43","44","45","46"],answer:"44"},
{subject:"Maths",question:"What is 22 + 24?",options:["45","46","47","48"],answer:"46"},
{subject:"Maths",question:"What is 23 + 25?",options:["47","48","49","50"],answer:"48"},
{subject:"Maths",question:"What is 24 + 26?",options:["49","50","51","52"],answer:"50"},
{subject:"Maths",question:"What is 25 + 27?",options:["51","52","53","54"],answer:"52"},
{subject:"Maths",question:"What is 10 − 3?",options:["5","6","7","8"],answer:"7"},
{subject:"Maths",question:"What is 12 − 5?",options:["6","7","8","9"],answer:"7"},
{subject:"Maths",question:"What is 14 − 6?",options:["7","8","9","10"],answer:"8"},
{subject:"Maths",question:"What is 16 − 7?",options:["8","9","10","11"],answer:"9"},
{subject:"Maths",question:"What is 18 − 9?",options:["8","9","10","11"],answer:"9"},
{subject:"Maths",question:"What is 20 − 8?",options:["10","11","12","13"],answer:"12"},
{subject:"Maths",question:"What is 22 − 7?",options:["13","14","15","16"],answer:"15"},
{subject:"Maths",question:"What is 24 − 9?",options:["14","15","16","17"],answer:"15"},
{subject:"Maths",question:"What is 26 − 11?",options:["14","15","16","17"],answer:"15"},
{subject:"Maths",question:"What is 28 − 13?",options:["14","15","16","17"],answer:"15"},
{subject:"Maths",question:"What is 30 − 10?",options:["18","19","20","21"],answer:"20"},
{subject:"Maths",question:"What is 32 − 12?",options:["19","20","21","22"],answer:"20"},
{subject:"Maths",question:"What is 34 − 14?",options:["19","20","21","22"],answer:"20"},
{subject:"Maths",question:"What is 36 − 16?",options:["19","20","21","22"],answer:"20"},
{subject:"Maths",question:"What is 38 − 18?",options:["19","20","21","22"],answer:"20"},
{subject:"Maths",question:"What is 40 − 15?",options:["24","25","26","27"],answer:"25"},
{subject:"Maths",question:"What is 42 − 17?",options:["24","25","26","27"],answer:"25"},
{subject:"Maths",question:"What is 44 − 19?",options:["24","25","26","27"],answer:"25"},
{subject:"Maths",question:"What is 46 − 21?",options:["24","25","26","27"],answer:"25"},
{subject:"Maths",question:"What is 48 − 23?",options:["24","25","26","27"],answer:"25"},
{subject:"Maths",question:"What is 50 − 20?",options:["28","29","30","31"],answer:"30"},
{subject:"Maths",question:"What is 52 − 22?",options:["28","29","30","31"],answer:"30"},
{subject:"Maths",question:"What is 54 − 24?",options:["28","29","30","31"],answer:"30"},
{subject:"Maths",question:"What is 56 − 26?",options:["28","29","30","31"],answer:"30"},
{subject:"Maths",question:"What is 58 − 28?",options:["28","29","30","31"],answer:"30"},
{subject:"Maths",question:"What is 2 × 3?",options:["5","6","7","8"],answer:"6"},
{subject:"Maths",question:"What is 3 × 4?",options:["10","11","12","13"],answer:"12"},
{subject:"Maths",question:"What is 4 × 5?",options:["18","19","20","21"],answer:"20"},
{subject:"Maths",question:"What is 5 × 6?",options:["28","29","30","31"],answer:"30"},
{subject:"Maths",question:"What is 6 × 7?",options:["40","41","42","43"],answer:"42"},
{subject:"Maths",question:"What is 7 × 8?",options:["54","55","56","57"],answer:"56"},
{subject:"Maths",question:"What is 8 × 9?",options:["70","71","72","73"],answer:"72"},
{subject:"Maths",question:"What is 9 × 6?",options:["52","53","54","55"],answer:"54"},
{subject:"Maths",question:"What is 10 × 5?",options:["48","49","50","51"],answer:"50"},
{subject:"Maths",question:"What is 11 × 4?",options:["42","43","44","45"],answer:"44"},
{subject:"Maths",question:"What is 12 × 3?",options:["34","35","36","37"],answer:"36"},
{subject:"Maths",question:"What is 13 × 2?",options:["24","25","26","27"],answer:"26"},
{subject:"Maths",question:"What is 14 × 2?",options:["26","27","28","29"],answer:"28"},
{subject:"Maths",question:"What is 15 × 2?",options:["28","29","30","31"],answer:"30"},
{subject:"Maths",question:"What is 16 × 2?",options:["30","31","32","33"],answer:"32"},
{subject:"Maths",question:"What is 3 × 9?",options:["25","26","27","28"],answer:"27"},
{subject:"Maths",question:"What is 4 × 9?",options:["34","35","36","37"],answer:"36"},
{subject:"Maths",question:"What is 5 × 9?",options:["43","44","45","46"],answer:"45"},
{subject:"Maths",question:"What is 6 × 9?",options:["52","53","54","55"],answer:"54"},
{subject:"Maths",question:"What is 7 × 9?",options:["61","62","63","64"],answer:"63"},
{subject:"Maths",question:"What is 8 × 7?",options:["54","55","56","57"],answer:"56"},
{subject:"Maths",question:"What is 9 × 8?",options:["70","71","72","73"],answer:"72"},
{subject:"Maths",question:"What is 10 × 8?",options:["78","79","80","81"],answer:"80"},
{subject:"Maths",question:"What is 11 × 6?",options:["64","65","66","67"],answer:"66"},
{subject:"Maths",question:"What is 12 × 5?",options:["58","59","60","61"],answer:"60"},
{subject:"Maths",question:"What is 12 ÷ 3?",options:["3","4","5","6"],answer:"4"},
{subject:"Maths",question:"What is 20 ÷ 5?",options:["3","4","5","6"],answer:"4"},
{subject:"Maths",question:"What is 18 ÷ 6?",options:["2","3","4","5"],answer:"3"},
{subject:"Maths",question:"What is 16 ÷ 4?",options:["3","4","5","6"],answer:"4"},
{subject:"Maths",question:"What is 24 ÷ 6?",options:["3","4","5","6"],answer:"4"},
{subject:"Maths",question:"What is 30 ÷ 5?",options:["5","6","7","8"],answer:"6"},
{subject:"Maths",question:"What is 36 ÷ 6?",options:["5","6","7","8"],answer:"6"},
{subject:"Maths",question:"What is 40 ÷ 8?",options:["4","5","6","7"],answer:"5"},
{subject:"Maths",question:"What is 45 ÷ 9?",options:["4","5","6","7"],answer:"5"},
{subject:"Maths",question:"What is 48 ÷ 6?",options:["7","8","9","10"],answer:"8"},
{subject:"Maths",question:"What is 54 ÷ 6?",options:["8","9","10","11"],answer:"9"},
{subject:"Maths",question:"What is 56 ÷ 7?",options:["7","8","9","10"],answer:"8"},
{subject:"Maths",question:"What is 63 ÷ 7?",options:["8","9","10","11"],answer:"9"},
{subject:"Maths",question:"What is 64 ÷ 8?",options:["7","8","9","10"],answer:"8"},
{subject:"Maths",question:"What is 72 ÷ 8?",options:["8","9","10","11"],answer:"9"},
{subject:"Maths",question:"What is 81 ÷ 9?",options:["8","9","10","11"],answer:"9"},
{subject:"Maths",question:"What is 90 ÷ 10?",options:["8","9","10","11"],answer:"9"},
{subject:"Maths",question:"What is 100 ÷ 10?",options:["9","10","11","12"],answer:"10"},
{subject:"Maths",question:"What is 84 ÷ 7?",options:["11","12","13","14"],answer:"12"},
{subject:"Maths",question:"What is 96 ÷ 8?",options:["11","12","13","14"],answer:"12"},
{subject:"Maths",question:"What is 108 ÷ 9?",options:["11","12","13","14"],answer:"12"},
{subject:"Maths",question:"What is 120 ÷ 10?",options:["11","12","13","14"],answer:"12"},
{subject:"Maths",question:"What is 132 ÷ 11?",options:["11","12","13","14"],answer:"12"},
{subject:"Maths",question:"What is 144 ÷ 12?",options:["11","12","13","14"],answer:"12"},
{subject:"Maths",question:"What is 150 ÷ 15?",options:["9","10","11","12"],answer:"10"},

{subject:"Science",question:"What gas do plants use for photosynthesis?",options:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],answer:"Carbon Dioxide"},
{subject:"Science",question:"What is the boiling point of water in Celsius?",options:["90°C","100°C","80°C","120°C"],answer:"100°C"},
{subject:"Science",question:"Which organ pumps blood in the human body?",options:["Lungs","Brain","Heart","Kidney"],answer:"Heart"},
{subject:"Science",question:"What part of the plant conducts photosynthesis?",options:["Root","Stem","Leaf","Flower"],answer:"Leaf"},
{subject:"Science",question:"Which gas is essential for breathing?",options:["Nitrogen","Oxygen","Carbon","Helium"],answer:"Oxygen"},
{subject:"Science",question:"What planet is known as the Red Planet?",options:["Earth","Venus","Mars","Jupiter"],answer:"Mars"},
{subject:"Science",question:"What is the hardest natural substance?",options:["Gold","Iron","Diamond","Silver"],answer:"Diamond"},
{subject:"Science",question:"Which vitamin is produced by sunlight?",options:["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],answer:"Vitamin D"},
{subject:"Science",question:"What organ helps us breathe?",options:["Heart","Liver","Lungs","Stomach"],answer:"Lungs"},
{subject:"Science",question:"What force pulls objects toward Earth?",options:["Magnetism","Gravity","Friction","Energy"],answer:"Gravity"},

{subject:"Science",question:"Which metal is liquid at room temperature?",options:["Iron","Mercury","Gold","Aluminium"],answer:"Mercury"},
{subject:"Science",question:"What do we call animals that eat plants?",options:["Carnivores","Herbivores","Omnivores","Insectivores"],answer:"Herbivores"},
{subject:"Science",question:"Which gas protects Earth from UV rays?",options:["Oxygen","Nitrogen","Ozone","Carbon Dioxide"],answer:"Ozone"},
{subject:"Science",question:"Which part of the body controls actions?",options:["Heart","Brain","Lungs","Kidney"],answer:"Brain"},
{subject:"Science",question:"What is H₂O commonly known as?",options:["Salt","Water","Oxygen","Hydrogen"],answer:"Water"},
{subject:"Science",question:"Which organ filters blood?",options:["Heart","Kidney","Liver","Lungs"],answer:"Kidney"},
{subject:"Science",question:"What gas is released during photosynthesis?",options:["Carbon Dioxide","Oxygen","Nitrogen","Hydrogen"],answer:"Oxygen"},
{subject:"Science",question:"What type of energy is light?",options:["Thermal","Electrical","Light","Chemical"],answer:"Light"},
{subject:"Science",question:"Which planet has rings?",options:["Mars","Earth","Saturn","Venus"],answer:"Saturn"},
{subject:"Science",question:"Which sense organ is used to see?",options:["Ear","Nose","Eye","Skin"],answer:"Eye"},

{subject:"Science",question:"What causes rusting?",options:["Water","Air","Oxygen","Salt"],answer:"Oxygen"},
{subject:"Science",question:"What is the center of the solar system?",options:["Earth","Moon","Sun","Mars"],answer:"Sun"},
{subject:"Science",question:"Which gas is most abundant in air?",options:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],answer:"Nitrogen"},
{subject:"Science",question:"What is solid ice called?",options:["Water","Steam","Ice","Mist"],answer:"Ice"},
{subject:"Science",question:"What organ digests food?",options:["Heart","Stomach","Brain","Lungs"],answer:"Stomach"},
{subject:"Science",question:"Which planet is closest to the Sun?",options:["Venus","Earth","Mercury","Mars"],answer:"Mercury"},
{subject:"Science",question:"What is the unit of force?",options:["Joule","Newton","Watt","Volt"],answer:"Newton"},
{subject:"Science",question:"Which blood cells fight disease?",options:["Red","White","Platelets","Plasma"],answer:"White"},
{subject:"Science",question:"What is the process of evaporation?",options:["Liquid to Gas","Gas to Liquid","Solid to Liquid","Liquid to Solid"],answer:"Liquid to Gas"},
{subject:"Science",question:"Which organ helps in hearing?",options:["Eye","Nose","Ear","Tongue"],answer:"Ear"},

{subject:"Science",question:"What is the largest organ in the human body?",options:["Heart","Skin","Liver","Brain"],answer:"Skin"},
{subject:"Science",question:"Which gas do humans exhale?",options:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],answer:"Carbon Dioxide"},
{subject:"Science",question:"What is energy stored in food called?",options:["Heat","Light","Chemical","Electrical"],answer:"Chemical"},
{subject:"Science",question:"Which animal is known as the Ship of the Desert?",options:["Horse","Camel","Elephant","Donkey"],answer:"Camel"},
{subject:"Science",question:"Which organ controls balance?",options:["Brain","Ear","Eye","Heart"],answer:"Ear"},
{subject:"Science",question:"Which planet is known for life?",options:["Mars","Venus","Earth","Jupiter"],answer:"Earth"},
{subject:"Science",question:"Which material attracts iron?",options:["Wood","Plastic","Magnet","Paper"],answer:"Magnet"},
{subject:"Science",question:"What part of plant absorbs water?",options:["Stem","Leaf","Root","Flower"],answer:"Root"},
{subject:"Science",question:"What type of animal is a frog?",options:["Reptile","Mammal","Amphibian","Bird"],answer:"Amphibian"},
{subject:"Science",question:"Which organ pumps oxygen to body?",options:["Brain","Heart","Lungs","Kidney"],answer:"Heart"},

{subject:"Science",question:"Which planet is the largest?",options:["Earth","Mars","Jupiter","Venus"],answer:"Jupiter"},
{subject:"Science",question:"Which organ helps in taste?",options:["Eye","Tongue","Nose","Ear"],answer:"Tongue"},
{subject:"Science",question:"What do bees collect from flowers?",options:["Water","Honey","Pollen","Seeds"],answer:"Pollen"},
{subject:"Science",question:"Which gas is used in balloons?",options:["Oxygen","Helium","Nitrogen","Hydrogen"],answer:"Helium"},
{subject:"Science",question:"What is molten rock called?",options:["Stone","Lava","Sand","Clay"],answer:"Lava"},
{subject:"Science",question:"Which animal lays eggs?",options:["Dog","Cat","Cow","Hen"],answer:"Hen"},
{subject:"Science",question:"Which vitamin helps blood clot?",options:["A","B","C","K"],answer:"K"},
{subject:"Science",question:"What part of body digests food?",options:["Heart","Stomach","Brain","Lung"],answer:"Stomach"},
{subject:"Science",question:"What gas do plants release at night?",options:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],answer:"Carbon Dioxide"},
{subject:"Science",question:"Which part protects the brain?",options:["Ribs","Skull","Spine","Chest"],answer:"Skull"},

{subject:"Science",question:"What is the source of energy for Earth?",options:["Moon","Stars","Sun","Wind"],answer:"Sun"},
{subject:"Science",question:"Which sense organ detects smell?",options:["Eye","Ear","Nose","Skin"],answer:"Nose"},
{subject:"Science",question:"Which organ stores urine?",options:["Kidney","Bladder","Liver","Heart"],answer:"Bladder"},
{subject:"Science",question:"Which material floats on water?",options:["Stone","Iron","Wood","Steel"],answer:"Wood"},
{subject:"Science",question:"What is the shape of Earth?",options:["Flat","Round","Cube","Triangle"],answer:"Round"},
{subject:"Science",question:"Which gas is needed for burning?",options:["Nitrogen","Oxygen","Carbon","Hydrogen"],answer:"Oxygen"},
{subject:"Science",question:"Which animal breathes through gills?",options:["Dog","Cat","Fish","Bird"],answer:"Fish"},
{subject:"Science",question:"Which organ helps digestion?",options:["Heart","Liver","Brain","Lung"],answer:"Liver"},
{subject:"Science",question:"What type of force is magnetism?",options:["Contact","Non-contact","Friction","Mechanical"],answer:"Non-contact"},
{subject:"Science",question:"Which planet is known as Earth's twin?",options:["Mars","Venus","Jupiter","Mercury"],answer:"Venus"},

{subject:"GK",question:"What is the capital of India?",options:["Mumbai","Delhi","Kolkata","Chennai"],answer:"Delhi"},
{subject:"GK",question:"Which is the largest continent?",options:["Africa","Asia","Europe","Australia"],answer:"Asia"},
{subject:"GK",question:"Which is the longest river in the world?",options:["Amazon","Ganga","Nile","Yangtze"],answer:"Nile"},
{subject:"GK",question:"Who is known as the Father of the Nation in India?",options:["Jawaharlal Nehru","Mahatma Gandhi","Subhas Chandra Bose","Bhagat Singh"],answer:"Mahatma Gandhi"},
{subject:"GK",question:"How many days are there in a leap year?",options:["364","365","366","367"],answer:"366"},
{subject:"GK",question:"Which planet is known as the Blue Planet?",options:["Mars","Venus","Earth","Neptune"],answer:"Earth"},
{subject:"GK",question:"What is the national animal of India?",options:["Lion","Tiger","Elephant","Leopard"],answer:"Tiger"},
{subject:"GK",question:"Which ocean is the largest?",options:["Indian","Atlantic","Pacific","Arctic"],answer:"Pacific"},
{subject:"GK",question:"Which country gifted the Statue of Liberty to the USA?",options:["France","England","Germany","Italy"],answer:"France"},
{subject:"GK",question:"How many colors are there in a rainbow?",options:["5","6","7","8"],answer:"7"},

{subject:"GK",question:"Which is the smallest continent?",options:["Europe","Australia","Antarctica","South America"],answer:"Australia"},
{subject:"GK",question:"Who wrote the national anthem of India?",options:["Rabindranath Tagore","Bankim Chandra","Sarojini Naidu","Subhash Bose"],answer:"Rabindranath Tagore"},
{subject:"GK",question:"Which is the national bird of India?",options:["Peacock","Sparrow","Eagle","Parrot"],answer:"Peacock"},
{subject:"GK",question:"What is the currency of Japan?",options:["Yen","Won","Dollar","Euro"],answer:"Yen"},
{subject:"GK",question:"Which country has the largest population?",options:["USA","India","China","Russia"],answer:"China"},
{subject:"GK",question:"Which festival is known as the Festival of Lights?",options:["Eid","Christmas","Diwali","Holi"],answer:"Diwali"},
{subject:"GK",question:"Who invented the telephone?",options:["Edison","Newton","Alexander Graham Bell","Tesla"],answer:"Alexander Graham Bell"},
{subject:"GK",question:"Which sport uses a bat and ball?",options:["Football","Hockey","Cricket","Tennis"],answer:"Cricket"},
{subject:"GK",question:"Which is the highest mountain in the world?",options:["K2","Mount Everest","Kangchenjunga","Makalu"],answer:"Mount Everest"},
{subject:"GK",question:"How many continents are there?",options:["5","6","7","8"],answer:"7"},

{subject:"GK",question:"Which is the national flower of India?",options:["Rose","Lotus","Sunflower","Lily"],answer:"Lotus"},
{subject:"GK",question:"What is the capital of France?",options:["Rome","Paris","Berlin","Madrid"],answer:"Paris"},
{subject:"GK",question:"Which animal is known as the King of the Jungle?",options:["Tiger","Lion","Elephant","Leopard"],answer:"Lion"},
{subject:"GK",question:"Which planet is closest to the Sun?",options:["Venus","Earth","Mercury","Mars"],answer:"Mercury"},
{subject:"GK",question:"Who was the first Prime Minister of India?",options:["Nehru","Gandhi","Patel","Ambedkar"],answer:"Jawaharlal Nehru"},
{subject:"GK",question:"Which is the national sport of India?",options:["Cricket","Football","Hockey","Kabaddi"],answer:"Hockey"},
{subject:"GK",question:"Which gas do humans breathe in?",options:["Nitrogen","Carbon Dioxide","Oxygen","Helium"],answer:"Oxygen"},
{subject:"GK",question:"Which is the largest desert in the world?",options:["Sahara","Gobi","Thar","Kalahari"],answer:"Sahara"},
{subject:"GK",question:"What is the capital of USA?",options:["New York","Washington DC","Chicago","Los Angeles"],answer:"Washington DC"},
{subject:"GK",question:"Which instrument measures temperature?",options:["Barometer","Thermometer","Hygrometer","Altimeter"],answer:"Thermometer"},

{subject:"GK",question:"Who discovered gravity?",options:["Newton","Einstein","Galileo","Tesla"],answer:"Newton"},
{subject:"GK",question:"Which country is famous for pyramids?",options:["India","Mexico","Egypt","China"],answer:"Egypt"},
{subject:"GK",question:"Which is the fastest land animal?",options:["Lion","Tiger","Cheetah","Leopard"],answer:"Cheetah"},
{subject:"GK",question:"Which day is celebrated as Independence Day in India?",options:["14 August","15 August","26 January","2 October"],answer:"15 August"},
{subject:"GK",question:"Which is the largest mammal?",options:["Elephant","Blue Whale","Giraffe","Rhino"],answer:"Blue Whale"},
{subject:"GK",question:"Which planet is known as the Morning Star?",options:["Mars","Venus","Jupiter","Saturn"],answer:"Venus"},
{subject:"GK",question:"Which is the capital of Rajasthan?",options:["Udaipur","Jodhpur","Jaipur","Ajmer"],answer:"Jaipur"},
{subject:"GK",question:"Which river is the longest in India?",options:["Ganga","Yamuna","Brahmaputra","Godavari"],answer:"Ganga"},
{subject:"GK",question:"Which bird cannot fly?",options:["Crow","Pigeon","Ostrich","Eagle"],answer:"Ostrich"},
{subject:"GK",question:"Which month has the least number of days?",options:["January","February","March","April"],answer:"February"},

{subject:"GK",question:"Who was the first President of India?",options:["Rajendra Prasad","Nehru","Radhakrishnan","Patel"],answer:"Rajendra Prasad"},
{subject:"GK",question:"Which is the largest ocean in the world?",options:["Atlantic","Indian","Pacific","Arctic"],answer:"Pacific"},
{subject:"GK",question:"Which country is known as the Land of Rising Sun?",options:["China","Japan","Korea","Thailand"],answer:"Japan"},
{subject:"GK",question:"Which is the smallest bone in the human body?",options:["Stapes","Femur","Ulna","Radius"],answer:"Stapes"},
{subject:"GK",question:"Which day is celebrated as Teachers Day in India?",options:["5 September","15 August","14 November","2 October"],answer:"5 September"},
{subject:"GK",question:"Which is the national tree of India?",options:["Neem","Peepal","Banyan","Mango"],answer:"Banyan"},
{subject:"GK",question:"What is the capital of China?",options:["Shanghai","Beijing","Wuhan","Nanjing"],answer:"Beijing"},
{subject:"GK",question:"Which metal is called the king of metals?",options:["Iron","Gold","Silver","Platinum"],answer:"Gold"},
{subject:"GK",question:"Which is the smallest planet?",options:["Mercury","Mars","Venus","Earth"],answer:"Mercury"},
{subject:"GK",question:"Which country has the Taj Mahal?",options:["Pakistan","India","Bangladesh","Nepal"],answer:"India"},

{subject:"English",question:"What is the synonym of Happy?",options:["Sad","Joyful","Angry","Tired"],answer:"Joyful"},
{subject:"English",question:"What is the antonym of Big?",options:["Large","Huge","Small","Tall"],answer:"Small"},
{subject:"English",question:"Choose the correct spelling.",options:["Recieve","Receive","Receve","Receivee"],answer:"Receive"},
{subject:"English",question:"Plural of Child is?",options:["Childs","Children","Childrens","Childes"],answer:"Children"},
{subject:"English",question:"Which is a noun?",options:["Run","Blue","Happiness","Quickly"],answer:"Happiness"},

{subject:"English",question:"What is the synonym of Fast?",options:["Slow","Quick","Late","Lazy"],answer:"Quick"},
{subject:"English",question:"What is the antonym of Hot?",options:["Warm","Cold","Heat","Cool"],answer:"Cold"},
{subject:"English",question:"Which is a verb?",options:["Beauty","Run","Blue","Happy"],answer:"Run"},
{subject:"English",question:"Plural of Mouse?",options:["Mouses","Mice","Mouse","Mices"],answer:"Mice"},
{subject:"English",question:"Choose the correct spelling.",options:["Definately","Definitely","Definitly","Definatly"],answer:"Definitely"},

{subject:"English",question:"What is the synonym of Angry?",options:["Calm","Furious","Happy","Quiet"],answer:"Furious"},
{subject:"English",question:"What is the antonym of Early?",options:["Soon","Late","Fast","Sharp"],answer:"Late"},
{subject:"English",question:"Which is an adjective?",options:["Run","Tall","Quickly","Happiness"],answer:"Tall"},
{subject:"English",question:"Plural of Foot?",options:["Foots","Feets","Feet","Foot"],answer:"Feet"},
{subject:"English",question:"Choose the correct spelling.",options:["Beautifull","Beautiful","Beutiful","Beautifal"],answer:"Beautiful"},

{subject:"English",question:"What is the synonym of Small?",options:["Tiny","Big","Huge","Large"],answer:"Tiny"},
{subject:"English",question:"What is the antonym of Strong?",options:["Powerful","Weak","Bold","Hard"],answer:"Weak"},
{subject:"English",question:"Which is a pronoun?",options:["Run","She","Blue","Quick"],answer:"She"},
{subject:"English",question:"Plural of Tooth?",options:["Tooths","Teeth","Toothes","Tooth"],answer:"Teeth"},
{subject:"English",question:"Choose the correct spelling.",options:["Goverment","Government","Govermant","Governmint"],answer:"Government"},

{subject:"English",question:"What is the synonym of Begin?",options:["End","Start","Finish","Close"],answer:"Start"},
{subject:"English",question:"What is the antonym of Dark?",options:["Black","Dim","Light","Shade"],answer:"Light"},
{subject:"English",question:"Which is an adverb?",options:["Quick","Quickly","Run","Happy"],answer:"Quickly"},
{subject:"English",question:"Plural of Man?",options:["Mans","Mens","Men","Man"],answer:"Men"},
{subject:"English",question:"Choose the correct spelling.",options:["Enviroment","Environment","Envirment","Enviornment"],answer:"Environment"},

{subject:"English",question:"What is the synonym of Brave?",options:["Coward","Fearful","Bold","Weak"],answer:"Bold"},
{subject:"English",question:"What is the antonym of Clean?",options:["Pure","Neat","Dirty","Fresh"],answer:"Dirty"},
{subject:"English",question:"Which is a conjunction?",options:["And","Run","Blue","Fast"],answer:"And"},
{subject:"English",question:"Plural of Woman?",options:["Womans","Women","Womens","Woman"],answer:"Women"},
{subject:"English",question:"Choose the correct spelling.",options:["Succesful","Successful","Succesfull","Successfull"],answer:"Successful"},

{subject:"English",question:"What is the synonym of Silent?",options:["Loud","Quiet","Noisy","Shout"],answer:"Quiet"},
{subject:"English",question:"What is the antonym of Long?",options:["Tall","Big","Short","Wide"],answer:"Short"},
{subject:"English",question:"Which is a preposition?",options:["Under","Run","Fast","Blue"],answer:"Under"},
{subject:"English",question:"Plural of Goose?",options:["Gooses","Geese","Goos","Goose"],answer:"Geese"},
{subject:"English",question:"Choose the correct spelling.",options:["Neccessary","Necessary","Necesary","Neccesary"],answer:"Necessary"},

{subject:"English",question:"What is the synonym of Smart?",options:["Clever","Dull","Slow","Weak"],answer:"Clever"},
{subject:"English",question:"What is the antonym of Old?",options:["Ancient","Young","Past","Aged"],answer:"Young"},
{subject:"English",question:"Which is an interjection?",options:["Wow","Run","Fast","Blue"],answer:"Wow"},
{subject:"English",question:"Plural of Ox?",options:["Oxes","Oxs","Oxen","Ox"],answer:"Oxen"},
{subject:"English",question:"Choose the correct spelling.",options:["Knowlege","Knowledge","Knowldge","Knowlegee"],answer:"Knowledge"},

{subject:"English",question:"What is the synonym of Rich?",options:["Poor","Wealthy","Weak","Low"],answer:"Wealthy"},
{subject:"English",question:"What is the antonym of Open?",options:["Wide","Close","Free","Shut"],answer:"Close"},
{subject:"English",question:"Which is a sentence?",options:["Run fast","Fast run","She runs fast","Running fast"],answer:"She runs fast"},
{subject:"English",question:"Plural of Leaf?",options:["Leafs","Leaves","Leafes","Leaf"],answer:"Leaves"},
{subject:"English",question:"Choose the correct spelling.",options:["Frend","Friend","Freind","Frient"],answer:"Friend"},

{subject:"English",question:"What is the synonym of Love?",options:["Hate","Fear","Care","Affection"],answer:"Affection"},
{subject:"English",question:"What is the antonym of Loud?",options:["Noisy","Silent","Shout","Cry"],answer:"Silent"},
{subject:"English",question:"Which is a question sentence?",options:["I run","Run fast","Do you run?","Running"],answer:"Do you run?"},
{subject:"English",question:"Plural of Knife?",options:["Knifes","Knives","Knife","Knifess"],answer:"Knives"},
{subject:"English",question:"Choose the correct spelling.",options:["Acheive","Achieve","Acheeve","Achive"],answer:"Achieve"},

{subject:"English",question:"What is the synonym of Calm?",options:["Angry","Quiet","Loud","Wild"],answer:"Quiet"},
{subject:"English",question:"What is the antonym of Soft?",options:["Hard","Smooth","Light","Gentle"],answer:"Hard"},
{subject:"English",question:"Which is a proper noun?",options:["city","boy","India","river"],answer:"India"},
{subject:"English",question:"Plural of Deer?",options:["Deers","Deer","Deeres","Dear"],answer:"Deer"},
{subject:"English",question:"Choose the correct spelling.",options:["Buisness","Business","Busines","Bussiness"],answer:"Business"},

{subject:"English",question:"What is the synonym of Honest?",options:["Truthful","Clever","Smart","Lazy"],answer:"Truthful"},
{subject:"English",question:"What is the antonym of Empty?",options:["Vacant","Full","Hollow","Clear"],answer:"Full"},
{subject:"English",question:"Which is a common noun?",options:["Ravi","Delhi","Boy","Ganga"],answer:"Boy"},
{subject:"English",question:"Plural of Sheep?",options:["Sheeps","Sheep","Shepes","Sheepes"],answer:"Sheep"},
{subject:"English",question:"Choose the correct spelling.",options:["Febuary","February","Februery","Febrary"],answer:"February"},

{subject:"English",question:"What is the synonym of Clean?",options:["Dirty","Pure","Messy","Bad"],answer:"Pure"},
{subject:"English",question:"What is the antonym of Tall?",options:["High","Short","Long","Big"],answer:"Short"},
{subject:"English",question:"Which is a helping verb?",options:["Run","Is","Play","Jump"],answer:"Is"},
{subject:"English",question:"Plural of Fish?",options:["Fishes","Fish","Fishs","Fishe"],answer:"Fish"},
{subject:"English",question:"Choose the correct spelling.",options:["Occassion","Occasion","Ocasion","Occassionn"],answer:"Occasion"},

{subject:"English",question:"What is the synonym of Fear?",options:["Bravery","Terror","Joy","Calm"],answer:"Terror"},
{subject:"English",question:"What is the antonym of Brave?",options:["Bold","Coward","Strong","Smart"],answer:"Coward"},
{subject:"English",question:"Which is an abstract noun?",options:["Table","Chair","Honesty","Book"],answer:"Honesty"},
{subject:"English",question:"Plural of Life?",options:["Lifes","Lives","Life","Lifs"],answer:"Lives"},
{subject:"English",question:"Choose the correct spelling.",options:["Seperate","Separate","Seprate","Separrate"],answer:"Separate"},

{subject:"English",question:"What is the synonym of Old?",options:["Young","Ancient","New","Fresh"],answer:"Ancient"},
{subject:"English",question:"What is the antonym of Win?",options:["Beat","Lose","Score","Play"],answer:"Lose"},
{subject:"English",question:"Which is a countable noun?",options:["Milk","Water","Book","Rice"],answer:"Book"},
{subject:"English",question:"Plural of Potato?",options:["Potatos","Potatoes","Potato","Potatoses"],answer:"Potatoes"},
{subject:"English",question:"Choose the correct spelling.",options:["Gaurd","Guard","Gaurde","Guared"],answer:"Guard"},

{subject:"English",question:"What is the synonym of Help?",options:["Assist","Harm","Stop","Block"],answer:"Assist"},
{subject:"English",question:"What is the antonym of Near?",options:["Close","Far","Around","Beside"],answer:"Far"},
{subject:"English",question:"Which is an uncountable noun?",options:["Apple","Pen","Sugar","Car"],answer:"Sugar"},
{subject:"English",question:"Plural of Hero?",options:["Heros","Heroes","Hero","Heroses"],answer:"Heroes"},
{subject:"English",question:"Choose the correct spelling.",options:["Tommorow","Tomorrow","Tomorow","Tomarrow"],answer:"Tomorrow"},

{subject:"English",question:"What is the synonym of Begin?",options:["Start","Close","End","Stop"],answer:"Start"},
{subject:"English",question:"What is the antonym of Rich?",options:["Wealthy","Poor","Strong","Smart"],answer:"Poor"},
{subject:"English",question:"Which sentence is correct?",options:["She go school","She goes school","She goes to school","She going school"],answer:"She goes to school"},
{subject:"English",question:"Plural of Baby?",options:["Babys","Babies","Baby","Babyes"],answer:"Babies"},
{subject:"English",question:"Choose the correct spelling.",options:["Calender","Calendar","Calandar","Calenderr"],answer:"Calendar"}
];
